// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Net.Http;
using Microsoft.Rest;
using TickTack;

namespace TickTack
{
    public partial class HouseOfTheFutureApiHost : ServiceClient<HouseOfTheFutureApiHost>, IHouseOfTheFutureApiHost
    {
        private Uri _baseUri;
        
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        public Uri BaseUri
        {
            get { return this._baseUri; }
            set { this._baseUri = value; }
        }
        
        private ServiceClientCredentials _credentials;
        
        /// <summary>
        /// Credentials for authenticating with the service.
        /// </summary>
        public ServiceClientCredentials Credentials
        {
            get { return this._credentials; }
            set { this._credentials = value; }
        }
        
        private IAccount _account;
        
        public virtual IAccount Account
        {
            get { return this._account; }
        }
        
        private IDevices _devices;
        
        public virtual IDevices Devices
        {
            get { return this._devices; }
        }
        
        private IIotRegister _iotRegister;
        
        public virtual IIotRegister IotRegister
        {
            get { return this._iotRegister; }
        }
        
        private IServiceLocator _serviceLocator;
        
        public virtual IServiceLocator ServiceLocator
        {
            get { return this._serviceLocator; }
        }
        
        private ITest _test;
        
        public virtual ITest Test
        {
            get { return this._test; }
        }
        
        private ITick _tick;
        
        public virtual ITick Tick
        {
            get { return this._tick; }
        }
        
        /// <summary>
        /// Initializes a new instance of the HouseOfTheFutureApiHost class.
        /// </summary>
        public HouseOfTheFutureApiHost()
            : base()
        {
            this._account = new Account(this);
            this._devices = new Devices(this);
            this._iotRegister = new IotRegister(this);
            this._serviceLocator = new ServiceLocator(this);
            this._test = new Test(this);
            this._tick = new Tick(this);
            this._baseUri = new Uri("http://hotf.azurewebsites.net:80");
        }
        
        /// <summary>
        /// Initializes a new instance of the HouseOfTheFutureApiHost class.
        /// </summary>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public HouseOfTheFutureApiHost(params DelegatingHandler[] handlers)
            : base(handlers)
        {
            this._account = new Account(this);
            this._devices = new Devices(this);
            this._iotRegister = new IotRegister(this);
            this._serviceLocator = new ServiceLocator(this);
            this._test = new Test(this);
            this._tick = new Tick(this);
            this._baseUri = new Uri("http://hotf.azurewebsites.net:80");
        }
        
        /// <summary>
        /// Initializes a new instance of the HouseOfTheFutureApiHost class.
        /// </summary>
        /// <param name='rootHandler'>
        /// Optional. The http client handler used to handle http transport.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public HouseOfTheFutureApiHost(HttpClientHandler rootHandler, params DelegatingHandler[] handlers)
            : base(rootHandler, handlers)
        {
            this._account = new Account(this);
            this._devices = new Devices(this);
            this._iotRegister = new IotRegister(this);
            this._serviceLocator = new ServiceLocator(this);
            this._test = new Test(this);
            this._tick = new Tick(this);
            this._baseUri = new Uri("http://hotf.azurewebsites.net:80");
        }
        
        /// <summary>
        /// Initializes a new instance of the HouseOfTheFutureApiHost class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public HouseOfTheFutureApiHost(Uri baseUri, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            this._baseUri = baseUri;
        }
        
        /// <summary>
        /// Initializes a new instance of the HouseOfTheFutureApiHost class.
        /// </summary>
        /// <param name='credentials'>
        /// Required. Credentials for authenticating with the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public HouseOfTheFutureApiHost(ServiceClientCredentials credentials, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this._credentials = credentials;
            
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }
        
        /// <summary>
        /// Initializes a new instance of the HouseOfTheFutureApiHost class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='credentials'>
        /// Required. Credentials for authenticating with the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public HouseOfTheFutureApiHost(Uri baseUri, ServiceClientCredentials credentials, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this._baseUri = baseUri;
            this._credentials = credentials;
            
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }
    }
}
