// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using HouseOfTheFuture.IoTHub.Host.Models;
using Microsoft.Rest;

namespace HouseOfTheFuture.IoTHub.Host
{
    public partial interface IAccount
    {
        /// <param name='register'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<string>> PostWithOperationResponseAsync(RegistrationDto register, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    }
}
