// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using HouseOfTheFuture.IoTHub.Host;
using Microsoft.Rest;

namespace HouseOfTheFuture.IoTHub.Host
{
    public partial interface ITicktack : IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        Uri BaseUri
        {
            get; set; 
        }
        
        /// <summary>
        /// Credentials for authenticating with the service.
        /// </summary>
        ServiceClientCredentials Credentials
        {
            get; set; 
        }
        
        IAccount Account
        {
            get; 
        }
        
        IIotRegister IotRegister
        {
            get; 
        }
        
        ITest Test
        {
            get; 
        }
    }
}
