// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using TickTack;
using TickTack.Models;

namespace TickTack
{
    public static partial class ServiceLocatorExtensions
    {
        /// <param name='operations'>
        /// Reference to the TickTack.IServiceLocator.
        /// </param>
        public static ServiceLocations Get(this IServiceLocator operations)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IServiceLocator)s).GetAsync();
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the TickTack.IServiceLocator.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<ServiceLocations> GetAsync(this IServiceLocator operations, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<TickTack.Models.ServiceLocations> result = await operations.GetWithOperationResponseAsync(cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
