// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Net.Http;
using HouseOfTheFuture.IoTHub.Host;
using Microsoft.Rest;

namespace HouseOfTheFuture.IoTHub.Host
{
    public partial class Ticktack : ServiceClient<Ticktack>, ITicktack
    {
        private Uri _baseUri;
        
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        public Uri BaseUri
        {
            get { return this._baseUri; }
            set { this._baseUri = value; }
        }
        
        private ServiceClientCredentials _credentials;
        
        /// <summary>
        /// Credentials for authenticating with the service.
        /// </summary>
        public ServiceClientCredentials Credentials
        {
            get { return this._credentials; }
            set { this._credentials = value; }
        }
        
        private IAccount _account;
        
        public virtual IAccount Account
        {
            get { return this._account; }
        }
        
        private IIotRegister _iotRegister;
        
        public virtual IIotRegister IotRegister
        {
            get { return this._iotRegister; }
        }
        
        private ITest _test;
        
        public virtual ITest Test
        {
            get { return this._test; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Ticktack class.
        /// </summary>
        public Ticktack()
            : base()
        {
            this._account = new Account(this);
            this._iotRegister = new IotRegister(this);
            this._test = new Test(this);
            this._baseUri = new Uri("https://microsoft-apiapp7d7289d8c2e244eaadcc92fe9bc03bd2.azurewebsites.net");
        }
        
        /// <summary>
        /// Initializes a new instance of the Ticktack class.
        /// </summary>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public Ticktack(params DelegatingHandler[] handlers)
            : base(handlers)
        {
            this._account = new Account(this);
            this._iotRegister = new IotRegister(this);
            this._test = new Test(this);
            this._baseUri = new Uri("https://microsoft-apiapp7d7289d8c2e244eaadcc92fe9bc03bd2.azurewebsites.net");
        }
        
        /// <summary>
        /// Initializes a new instance of the Ticktack class.
        /// </summary>
        /// <param name='rootHandler'>
        /// Optional. The http client handler used to handle http transport.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public Ticktack(HttpClientHandler rootHandler, params DelegatingHandler[] handlers)
            : base(rootHandler, handlers)
        {
            this._account = new Account(this);
            this._iotRegister = new IotRegister(this);
            this._test = new Test(this);
            this._baseUri = new Uri("https://microsoft-apiapp7d7289d8c2e244eaadcc92fe9bc03bd2.azurewebsites.net");
        }
        
        /// <summary>
        /// Initializes a new instance of the Ticktack class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public Ticktack(Uri baseUri, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            this._baseUri = baseUri;
        }
        
        /// <summary>
        /// Initializes a new instance of the Ticktack class.
        /// </summary>
        /// <param name='credentials'>
        /// Required. Credentials for authenticating with the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public Ticktack(ServiceClientCredentials credentials, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this._credentials = credentials;
            
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }
        
        /// <summary>
        /// Initializes a new instance of the Ticktack class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='credentials'>
        /// Required. Credentials for authenticating with the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public Ticktack(Uri baseUri, ServiceClientCredentials credentials, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this._baseUri = baseUri;
            this._credentials = credentials;
            
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }
    }
}
