// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace TickTack.Models
{
    public partial class DeviceLinks
    {
        private string _self;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Self
        {
            get { return this._self; }
            set { this._self = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the DeviceLinks class.
        /// </summary>
        public DeviceLinks()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken selfValue = inputObject["self"];
                if (selfValue != null && selfValue.Type != JTokenType.Null)
                {
                    this.Self = ((string)selfValue);
                }
            }
        }
    }
}
