// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;
using TickTack.Models;

namespace TickTack.Models
{
    public partial class DeviceDto
    {
        private string _description;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Description
        {
            get { return this._description; }
            set { this._description = value; }
        }
        
        private string _id;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ID
        {
            get { return this._id; }
            set { this._id = value; }
        }
        
        private DeviceLinks _links;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DeviceLinks Links
        {
            get { return this._links; }
            set { this._links = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the DeviceDto class.
        /// </summary>
        public DeviceDto()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken descriptionValue = inputObject["description"];
                if (descriptionValue != null && descriptionValue.Type != JTokenType.Null)
                {
                    this.Description = ((string)descriptionValue);
                }
                JToken idValue = inputObject["id"];
                if (idValue != null && idValue.Type != JTokenType.Null)
                {
                    this.ID = ((string)idValue);
                }
                JToken linksValue = inputObject["links"];
                if (linksValue != null && linksValue.Type != JTokenType.Null)
                {
                    DeviceLinks deviceLinks = new DeviceLinks();
                    deviceLinks.DeserializeJson(linksValue);
                    this.Links = deviceLinks;
                }
            }
        }
    }
}
