// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace TickTack.Models
{
    public partial class GetDevicesLinks
    {
        private string _sync;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Sync
        {
            get { return this._sync; }
            set { this._sync = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the GetDevicesLinks class.
        /// </summary>
        public GetDevicesLinks()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken syncValue = inputObject["sync"];
                if (syncValue != null && syncValue.Type != JTokenType.Null)
                {
                    this.Sync = ((string)syncValue);
                }
            }
        }
    }
}
