// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Rest;
using Newtonsoft.Json.Linq;
using TickTack.Models;

namespace TickTack.Models
{
    public partial class GetDevicesResponse
    {
        private IList<DeviceDto> _devices;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<DeviceDto> Devices
        {
            get { return this._devices; }
            set { this._devices = value; }
        }
        
        private GetDevicesLinks _links;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public GetDevicesLinks Links
        {
            get { return this._links; }
            set { this._links = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the GetDevicesResponse class.
        /// </summary>
        public GetDevicesResponse()
        {
            this.Devices = new LazyList<DeviceDto>();
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken devicesSequence = ((JToken)inputObject["devices"]);
                if (devicesSequence != null && devicesSequence.Type != JTokenType.Null)
                {
                    foreach (JToken devicesValue in ((JArray)devicesSequence))
                    {
                        DeviceDto deviceDto = new DeviceDto();
                        deviceDto.DeserializeJson(devicesValue);
                        this.Devices.Add(deviceDto);
                    }
                }
                JToken linksValue = inputObject["links"];
                if (linksValue != null && linksValue.Type != JTokenType.Null)
                {
                    GetDevicesLinks getDevicesLinks = new GetDevicesLinks();
                    getDevicesLinks.DeserializeJson(linksValue);
                    this.Links = getDevicesLinks;
                }
            }
        }
    }
}
