// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace TickTack.Models
{
    public partial class PostRequest
    {
        private string _hubId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string HubId
        {
            get { return this._hubId; }
            set { this._hubId = value; }
        }
        
        private string _sensorId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string SensorId
        {
            get { return this._sensorId; }
            set { this._sensorId = value; }
        }
        
        private DateTimeOffset? _timestamp;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? Timestamp
        {
            get { return this._timestamp; }
            set { this._timestamp = value; }
        }
        
        private double? _value;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public double? Value
        {
            get { return this._value; }
            set { this._value = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the PostRequest class.
        /// </summary>
        public PostRequest()
        {
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type PostRequest
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.HubId != null)
            {
                outputObject["hubId"] = this.HubId;
            }
            if (this.SensorId != null)
            {
                outputObject["sensorId"] = this.SensorId;
            }
            if (this.Timestamp != null)
            {
                outputObject["timestamp"] = this.Timestamp.Value;
            }
            if (this.Value != null)
            {
                outputObject["value"] = this.Value.Value;
            }
            return outputObject;
        }
    }
}
