// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace TickTack.Models
{
    public partial class ServiceLocations
    {
        private string _devices;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Devices
        {
            get { return this._devices; }
            set { this._devices = value; }
        }
        
        private string _registerDevice;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string RegisterDevice
        {
            get { return this._registerDevice; }
            set { this._registerDevice = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ServiceLocations class.
        /// </summary>
        public ServiceLocations()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken devicesValue = inputObject["devices"];
                if (devicesValue != null && devicesValue.Type != JTokenType.Null)
                {
                    this.Devices = ((string)devicesValue);
                }
                JToken registerDeviceValue = inputObject["registerDevice"];
                if (registerDeviceValue != null && registerDeviceValue.Type != JTokenType.Null)
                {
                    this.RegisterDevice = ((string)registerDeviceValue);
                }
            }
        }
    }
}
