// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace HouseOfTheFuture.IoTHub.Models
{
    public partial class RegisterIotDeviceRequest
    {
        private string _currentDeviceId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string CurrentDeviceId
        {
            get { return this._currentDeviceId; }
            set { this._currentDeviceId = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the RegisterIotDeviceRequest class.
        /// </summary>
        public RegisterIotDeviceRequest()
        {
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type RegisterIotDeviceRequest
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.CurrentDeviceId != null)
            {
                outputObject["currentDeviceId"] = this.CurrentDeviceId;
            }
            return outputObject;
        }
    }
}
